### ISSUE TITLE
No moduled named 'cli'

### ISSUE THREAD

**Issue by ariselseng** [douglascamata/passman_cli#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/passman", line 9, in <module>
    load_entry_point('passman-cli==0.0.1', 'console_scripts', 'passman')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/passman_cli-0.0.1-py3.5.egg/passman_cli/entrypoint.py", line 4, in <module>
    from cli import vault, credential
ImportError: No module named 'cli'
```

Installed with sudo python3 setup.py install, on Ubuntu 16.04.

**Comment by douglascamata** [comment]
@cowai can you try with Python 2.7, please? I saw that you had Python 3.5 and there is a breaking change between these versions with regards to relative imports.

**Comment by ariselseng** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/passman", line 9, in <module>
    load_entry_point('passman-cli==0.0.1', 'console_scripts', 'passman')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/passman_cli-0.0.1-py2.7.egg/passman_cli/entrypoint.py", line 4, in <module>
    from cli import vault, credential
ImportError: No module named cli
```

**Comment by douglascamata** [comment]
@cowai you can use it properly now, I fixed the issue. It was related to the package build. Just pull from master and install it again, please.
